### PR TITLE
Fix incorrect cyclic dependency detection

### LINKED ISSUE #213: incorrect cycle detection
**Describe the bug**
The cycle detection doesn't like the fact that I have a leaf node that is a dependency of an intermediate node and a dependency of the root.

**To Reproduce**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" xmlns:dmndi="https://www.omg.org/spec/DMN/20191111/DMNDI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" id="Definitions_0h9zlqh" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" exporter="Camunda Modeler" exporterVersion="5.10.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.2.0">
  <decision id="Decision_0lsyapa" name="C">
    <variable id="InformationItem_0s8k0bl" name="out" />
    <informationRequirement id="InformationRequirement_1rlbqu9">
      <requiredDecision href="#Decision_0fqzk9r" />
    </informationRequirement>
    <informationRequirement id="InformationRequirement_05m4j2x">
      <requiredDecision href="#Decision_1m0vnmw" />
    </informationRequirement>
    <literalExpression id="LiteralExpression_04arz50">
      <text>[a, b]</text>
    </literalExpression>
  </decision>
  <decision id="Decision_1m0vnmw" name="B">
    <variable id="InformationItem_16zbv4v" name="b" />
    <informationRequirement id="InformationRequirement_00uf5b7">
      <requiredDecision href="#Decision_0fqzk9r" />
    </informationRequirement>
    <literalExpression id="LiteralExpression_0wt75p4">
      <text>a + 1</text>
    </literalExpression>
  </decision>
  <decision id="Decision_0fqzk9r" name="A">
    <variable id="InformationItem_0kwllv5" name="a" />
    <literalExpression id="LiteralExpression_10sjfdq">
      <text>1</text>
    </literalExpression>
  </decision>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram>
      <dmndi:DMNEdge id="DMNEdge_0tire0n" dmnElementRef="InformationRequirement_00uf5b7">
        <di:waypoint x="250" y="460" />
        <di:waypoint x="470" y="380" />
        <di:waypoint x="470" y="360" />
      </dmndi:DMNEdge>
      <dmndi:DMNEdge id="DMNEdge_1qeflao" dmnElementRef="InformationRequirement_1rlbqu9">
        <di:waypoint x="250" y="460" />
        <di:waypoint x="240" y="180" />
        <di:waypoint x="240" y="160" />
      </dmndi:DMNEdge>
      <dmndi:DMNEdge id="DMNEdge_1j44nm2" dmnElementRef="InformationRequirement_05m4j2x">
        <di:waypoint x="470" y="280" />
        <di:waypoint x="300" y="180" />
        <di:waypoint x="300" y="160" />
      </dmndi:DMNEdge>
      <dmndi:DMNShape id="DMNShape_0elqq7s" dmnElementRef="Decision_0lsyapa">
        <dc:Bounds height="80" width="180" x="180" y="80" />
      </dmndi:DMNShape>
      <dmndi:DMNShape id="DMNShape_182794f" dmnElementRef="Decision_1m0vnmw">
        <dc:Bounds height="80" width="180" x="380" y="280" />
      </dmndi:DMNShape>
      <dmndi:DMNShape id="DMNShape_0321hm2" dmnElementRef="Decision_0fqzk9r">
        <dc:Bounds height="80" width="180" x="160" y="460" />
      </dmndi:DMNShape>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
</definitions>

```

**Expected behavior**
The xml above should not throw (and works with the previous version of the parser and deployed on zeebe 8.1.x).

**Environment**
* DMN engine version: `1.8.0`

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

image
In this model there is no cyclic dependency. The parser incorrectly gives a warning that there is a cyclic dependency.

The cause lays in the cyclic dependency check. This check takes a list of decisions it still needs to visit. It builds this list from the dependencies of previous decisions that have been checked.
The scoping of this check is wrong.  It checks the dependencies in a cyclic way for the entire DRG. With each cycle we append to the visited elements. Upon reaching an end state, we do not clear this list of visited elements.

For the example DRG this means:

1. We check for cyclic dependencies in C
2. We check for cyclic dependencies in A (visited C)
3. A doesn't have any more dependencies, yet we append it to the list of visited elements and continue with the other decisions
4. We check for cyclic dependencies in B (visited C and A)
5. B finds a dependency on A, we've already visited A. As a result we incorrectly assume a cyclic dependency here.

This PR fixes the scoping by not passing a list of decisions to visit, but instead keeping it scoped to a single one. By checking if any dependencies exist with a cycle for this decision we don't run into the issue mentioned above.

## Related issues

closes #213

### CODE REVIEW

File: src/main/scala/org/camunda/dmn/parser/DmnParser.scala [hunk 1]
```diff
@@ -153,24 +153,19 @@ class DmnParser(
...
-      case Nil => false
-      case element :: _ if visited.contains(element) => true
-      case element :: tail => hasDependencyCycle(
-        visit = tail ++ dependencies.getOrElse(element, Nil),
-        visited = visited + element,
-        dependencies = dependencies
-      )
+      case element if visited.contains(element) => true
+      case element => dependencies.getOrElse(element, Nil).exists(dependency =>
+        hasDependencyCycle(dependency, visited + element, dependencies))
```
Comment (remcowesterhoud) [inline src/main/scala/org/camunda/dmn/parser/DmnParser.scala:168]: ℹ️ I kept this as pattern matching. This could also be switched to a simple if-else:

```java
    if (visited.contains(visit)) {
       true
     } else {
       dependencies.getOrElse(visit, Nil).exists(dependency =>
         hasDependencyCycle(dependency, visited + visit, dependencies)
       )
     }
```

This is similar to what we've had before [it got broken during a refactoring](https://github.com/camunda/dmn-scala/pull/207/commits/3161483aebfb5aef90e01fd32a82fe54e231aa3f#diff-36c33ab259b225915e1f3e920b87002f85d9c6a4bc5e97c0475003b19daf1344L165). Let me know what you prefer!

Comment (saig0) [reply src/main/scala/org/camunda/dmn/parser/DmnParser.scala:168]: Let's switch to the if-else block. :+1: 
The pattern matching doesn't bring value in this form. Unfortunately, no tail recursion anymore. But it is hard. :laughing: 

:wrench: We could use named parameters for the recursive call.

```scala
    if (visited.contains(visit)) {
       true
     } else {
       dependencies.getOrElse(visit, Nil).exists(dependency =>
         hasDependencyCycle(
           visit = dependency, 
           visited = visited + visit, 
           dependencies = dependencies
         )
       )
     }
```

**Review by saig0 — APPROVED** [review]
@remcowesterhoud good job. :+1: 

We can apply your suggestions. Then, it's ready to merge. :rocket:
