### PR TITLE
fix: Handle the invocation of a non-existing decision

### LINKED ISSUE #135: eval with unknown decision id leads to NoSuchElementException
**Describe the bug**
When I try to eval using a ParsedDmn, but with a `decisionId` that does not occur in the provided ParsedDmn, then the following exception is thrown:

```
java.util.NoSuchElementException: last of empty list

	at scala.collection.immutable.Nil$.last(List.scala:665)
	at scala.collection.immutable.Nil$.last(List.scala:661)
	at org.camunda.dmn.Audit$AuditLog.<init>(Audit.scala:17)
	at org.camunda.dmn.DmnEngine.$anonfun$eval$4(DmnEngine.scala:188)
	at scala.Option.getOrElse(Option.scala:201)
	at org.camunda.dmn.DmnEngine.eval(DmnEngine.scala:185)
	at org.camunda.dmn.DmnEngine.eval(DmnEngine.scala:220)
```

**To Reproduce**
- parse a simple dmn
- call `eval(dmn: ParsedDmn, decisionId: String, variables: java.util.Map[String, Object]): DecisionResult` with the parsed dmn, a decisionId that does not occur in the provided dmn, and an empty Map as variables.
- the exception is thrown

**Expected behavior**
A Failure result: `Failure(s"no decision found with id '$decisionId'")`

**Environment**
* DMN engine version: `1.7.1`
* Integration:
  * Camunda Cloud/Zeebe: personal development branch

### PR DESCRIPTION
**Pull request by saig0**
## Description

If a decision is invoked with a non-existing decision id, the engine returns a failure with an empty audit log. This caused an exception because the audit log couldn't handle an empty list.

Remove the public properties `rootEntry` and `requiredEntries` from the audit log. These properties don't work if the audit log entries are empty.

Note that the property `rootEntry` may contain an audit log entry but no from the root decision. If the evaluation of a required decision fails, the engine doesn't add an entry for the root decision.

## Related issues

closes #135

### CODE REVIEW

File: src/main/scala/org/camunda/dmn/Audit.scala [hunk 1]
```diff
@@ -27,11 +27,7 @@ object Audit {
     def onFailure(log: AuditLog)
   }
 
-  case class AuditLog(dmn: ParsedDmn, entries: List[AuditLogEntry]) {
-
-    val rootEntry = entries.last
```
Comment (remcowesterhoud) [inline src/main/scala/org/camunda/dmn/Audit.scala:32]: ❓ Why was `rootEntry` the last entry of the list? I realise it's gone and I don't really need to worry about it, but it seems odd that the root is the tail of the list instead of head.

**Review by remcowesterhoud — APPROVED** [review]
Thanks for the clear explanation and commit messages 👍 

I have one unrelated question to understand why the code as the way it was before. The changes all LGTM!

Do we have bors here?
bors merge

File: src/main/scala/org/camunda/dmn/Audit.scala (hunk 1 above)
Comment (saig0) [reply src/main/scala/org/camunda/dmn/Audit.scala:32]: Good question. The entries are in the order of the evaluation. Since all required decisions are evaluated before the root/called decision, the root decision is at the end. 

As an alternative, we could return the log as an evaluation tree that reflects the requirements as leaves. The structure and logic would be more complex but possible. 

The current structure seems to work. But we could change it if we see any needs.

**Comment by saig0** [comment]
@remcowesterhoud thank you for your fast review. :bow: 

> Do we have bors here? < I guess not smile

Not yet. But it would be nice to have. :sweat_smile:
